Repository KNU-HAEDAL-Website/frontend-v2, pull requests merged in 2024-12, with the labels that each got.

#29 issue#28 ESLint, Build 테스트를 위한 ci script 작성
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .prettierignore
  package-lock.json
  pnpm-lock.yaml
Labels: ⚙️ setting

#31 issue#4 내비게이션 메뉴명 변경
  src/app/(main)/_components/Header/Navigation/index.tsx
  src/app/(main)/activity/_components/ActivityBreadcrumb/index.tsx
  src/app/(main)/notice/_components/NoticeBoardHero/index.tsx
  src/app/(main)/notice/create-post/_components/CreateNoticePostHero/index.tsx
  src/app/(main)/notice/posts/[postId]/_components/NotciePostHero/index.tsx
Labels: 📦 chore

#40 Fix: FormField 컴포넌트 client render 버그 수정
  src/components/feature/post/form-field/FormField.tsx
Labels: 🛠️ fix

#48 Fix: 헤더 UI 깨짐 버그 수정
  next.config.mjs
  src/app/(main)/_components/header/navigation/MobileNavigation.tsx
  src/app/(main)/_components/header/profile-button/dropdown-menu/DropdownMenu.tsx
  src/service/server/activity/add-activity.ts
  src/service/server/auth/login.ts
  src/service/server/auth/signup.ts
  tsconfig.json
Labels: 🛠️ fix

#49 issue#8 게시판 생성 버그 픽스
  src/app/(main)/activity/[semesterName]/[activityId]/create-board/_components/form/MultipleMemberSelect.tsx
  src/schema/auth.ts
  src/schema/board.ts
  src/schema/post.ts
  src/service/server/auth/signup.ts
Labels: 🛠️ fix, 📦 chore

#44 issue#37 멤버 페이지 UI 구현
  src/app/(main)/_components/header/navigation/Navigation.tsx
  src/app/(main)/member/_components/index.ts
  src/app/(main)/member/_components/member-card/FlipCard.tsx
  src/app/(main)/member/_components/member-card/MemberCard.tsx
  src/app/(main)/member/_components/member-card/index.ts
  src/app/(main)/member/page.tsx
  src/components/common/IconButton.tsx
  src/components/common/index.ts
  src/components/ui/label.tsx
  tailwind.config.ts
Labels: 🎨 desgin

#51 issue#50 푸터 디자인 변경
  src/app/(main)/_components/footer/Footer.tsx
  src/app/(main)/_components/footer/FooterDetail.tsx
  src/app/(main)/_components/footer/LinkIcon.tsx
Labels: 🎨 desgin

#42 issue#41 마이페이지 ui 구현
  src/app/(main)/_components/header/profile-button/dropdown-menu/DropdownMenu.tsx
  src/app/(main)/mypage/_components/index.ts
  src/app/(main)/mypage/_components/user-img/UserImgSection.tsx
  src/app/(main)/mypage/_components/user-img/index.ts
  src/app/(main)/mypage/_components/user-info/UserInfoSection.tsx
  src/app/(main)/mypage/_components/user-info/index.ts
  src/app/(main)/mypage/_hooks/index.ts
  src/app/(main)/mypage/_hooks/useEditProfileIntro.ts
  src/app/(main)/mypage/_hooks/useSocialInfo.ts
  src/app/(main)/mypage/page.tsx
  src/components/ui/button.tsx
  src/schema/mypage.ts
Labels: 🎨 desgin

#56 issue#43 icon 파일 형식 변경
  public/asset/icon/Email.svg
  public/asset/icon/Github.svg
  public/asset/icon/Instagram.svg
  src/app/(main)/_components/footer/LinkIcon.tsx
Labels: 📦 chore

#62 issue#57 Footer 모바일 뷰 디자인 수정
  src/app/(main)/_components/footer/ChannelIcons.tsx
  src/app/(main)/_components/footer/Footer.tsx
  src/app/(main)/_components/footer/FooterDetail.tsx
Labels: 🎨 desgin

#64 issue#9 행사 페이지 UI 변경 (2)
  package-lock.json
  package.json
  src/app/(main)/event/_components/board-area/BoardArea.tsx
  src/app/(main)/event/_components/board-area/BoardHero.tsx
  src/app/(main)/event/_components/board-area/CreatePostButton.tsx
  src/app/(main)/event/_components/board-area/Gallery.tsx
  src/app/(main)/event/_components/board-area/PostList.tsx
  src/app/(main)/event/_components/board-area/ViewSelector.tsx
  src/app/(main)/event/_components/board-area/index.ts
  src/app/(main)/event/_components/carousel/Carousel.tsx
  src/app/(main)/event/_components/carousel/index.ts
  src/app/(main)/event/_components/index.ts
  src/app/(main)/event/_components/instagram-area/InstagramArea.tsx
  src/app/(main)/event/_components/instagram-area/index.ts
  src/app/(main)/event/board/create-post/_components/form/Form.tsx
  src/app/(main)/event/board/create-post/_components/form/index.ts
  src/app/(main)/event/board/create-post/_components/hero/Hero.tsx
  src/app/(main)/event/board/create-post/_components/hero/index.ts
  src/app/(main)/event/board/create-post/_components/index.ts
  src/app/(main)/event/board/create-post/layout.tsx
  src/app/(main)/event/board/create-post/page.tsx
  src/app/(main)/event/board/layout.tsx
  src/app/(main)/event/board/posts/[postId]/_components/hero/Hero.tsx
  src/app/(main)/event/board/posts/[postId]/_components/hero/index.ts
  src/app/(main)/event/board/posts/[postId]/_components/index.ts
  src/app/(main)/event/board/posts/[postId]/_components/post-detail/PostDetail.tsx
  src/app/(main)/event/board/posts/[postId]/_components/post-detail/index.ts
  src/app/(main)/event/board/posts/[postId]/page.tsx
  src/app/(main)/event/page.tsx
  src/schema/post.ts
Labels: ♻️ refactor

#65 issue#53 마이페이지 form 기능 수정
  src/app/(main)/mypage/_assets/haedal-logo.png
  src/app/(main)/mypage/_components/index.ts
  src/app/(main)/mypage/_components/user-img/UserImgSection.tsx
  src/app/(main)/mypage/_components/user-img/index.ts
  src/app/(main)/mypage/_components/user-info/UserInfoSection.tsx
  src/app/(main)/mypage/_components/user-social-info/UserSocialInfoSection.tsx
  src/app/(main)/mypage/_components/user-social-info/index.ts
  src/app/(main)/mypage/page.tsx
  src/schema/mypage.ts
Labels: 🎨 desgin

#66 issue#63 관리자 페이지 error boundary 추가
  package-lock.json
  package.json
  src/app/(main)/admin/member/_components/approve-table/Button.tsx
  src/app/(main)/admin/member/_components/change-role-table/Dialog.tsx
  src/app/(main)/admin/member/_components/change-role-table/DialogForm.tsx
  src/app/(main)/admin/member/_components/change-role-table/RoleRadioGroup.tsx
  src/app/(main)/admin/member/_components/expel-table/DialogForm.tsx
  src/app/(main)/admin/member/_components/expel-table/Table.tsx
  src/app/(main)/admin/member/layout.tsx
  src/app/(main)/admin/semester/_components/activity-accordion/ActivityList.tsx
  src/app/(main)/admin/semester/_components/activity-accordion/AddForm.tsx
  src/app/(main)/admin/semester/_components/semester-list/AddDialogForm.tsx
  src/app/(main)/admin/semester/_components/semester-list/DeleteDialog.tsx
  src/app/(main)/admin/semester/layout.tsx
  src/app/(main)/admin/semester/page.tsx
  src/components/feature/admin/error-fallback/ErrorFallback.tsx
  src/components/feature/admin/error-fallback/index.ts
  src/components/feature/admin/index.ts
  src/components/feature/skeleton/SemesterPage.tsx
  src/components/feature/skeleton/index.ts
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/lib/query-client.tsx
  src/utils/convert-role.ts
Labels: 🎉 feat

#69 issue#61 활동 페이지 리다이렉트 로직 수정
  src/app/(main)/activity/[semesterId]/[activityId]/_components/acitivity-list/ActivityList.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/acitivity-list/ActivityListSkeleton.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/acitivity-list/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/_components/board-list/BoardList.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/board-list/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/_components/create-board-button/CreateBoardButton.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/create-board-button/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/_components/hero/Hero.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/hero/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/_components/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/_components/semester-list/SemesterList.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/semester-list/SemesterListSkeleton.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/semester-list/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/_components/semester/RedirectSemester.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/semester/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/layout.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/page.tsx
  src/app/(main)/admin/semester/_components/activity-accordion/ActivityList.tsx
  src/components/feature/skeleton/Semester.tsx
  src/components/feature/skeleton/index.ts
  src/service/api/activity/activity.ts
  src/service/models/Semesters.ts
  src/service/models/data-contracts.ts
Labels: ♻️ refactor
