Repository KNU-HAEDAL-Website/frontend-v2, pull requests merged in 2025-01, with the labels that each got.

#67 issue#38 마이페이지 API 연결
  src/app/(main)/mypage/_components/user-info/UserInfoSection.tsx
  src/app/(main)/mypage/_components/user-social-info/UserSocialInfoSection.tsx
  src/app/(main)/mypage/_hooks/index.ts
  src/app/(main)/mypage/_hooks/useEditProfileIntro.ts
  src/app/(main)/mypage/_hooks/useSocialInfo.ts
  src/app/(main)/mypage/page.tsx
  src/app/auth/login/_components/form/Form.tsx
  src/schema/mypage.ts
  src/service/api/mypage/index.ts
  src/service/api/mypage/mypage.ts
  src/service/models/data-contracts.ts
  src/store/myInfo.ts
Labels: 🎉 feat, 🛠️ fix

#77 Fix: 활동 페이지 404 에러 이슈
  src/app/(main)/_components/header/navigation/Navigation.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/ErrorFallback.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/acitivity-list/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/_components/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/_components/semester-list/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/layout.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/page.tsx
  src/app/(main)/activity/[semesterId]/page.tsx
  src/app/(main)/activity/_components/ErrorFallback.tsx
  src/app/(main)/activity/_components/index.ts
  src/app/(main)/activity/layout.tsx
  src/app/(main)/activity/page.tsx
  src/components/feature/activity/acitivity-list/ActivityList.tsx
  src/components/feature/activity/acitivity-list/Skeleton.tsx
  src/components/feature/activity/acitivity-list/index.ts
  src/components/feature/activity/bread-crumb/BreadCrumb.tsx
  src/components/feature/activity/bread-crumb/index.ts
  src/components/feature/activity/hero/Hero.tsx
  src/components/feature/activity/hero/index.ts
  src/components/feature/activity/index.ts
  src/components/feature/activity/name-label/NameLabel.tsx
  src/components/feature/activity/name-label/index.ts
  src/components/feature/activity/semester-list/Sekeleton.tsx
  src/components/feature/activity/semester-list/SemesterList.tsx
  src/components/feature/activity/semester-list/index.ts
  src/service/api/activity/activity.ts
  src/service/api/semester/semester.ts
Labels: 🛠️ fix

#72 issue#71 로그아웃 toast
  src/app/(main)/_components/header/profile-button/dropdown-menu/LogoutButton.tsx
Labels: 🎉 feat

#80 issue/#73 404 페이지, NotFound 컴포넌트 추가
  src/app/[...404]/page.tsx
  src/components/common/index.ts
  src/components/common/not-found/NotFound.tsx
  src/components/common/not-found/index.ts
Labels: 🎉 feat

#83 issue#82 게시글 리팩토링
  .gitignore
  package-lock.json
  package.json
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/_components/BoardHero.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/_components/CreateButton.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/_components/PostList.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/PostForm.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/form/Form.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/form/date-field-dialog/DateFieldDialog.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/form/date-field-dialog/TriggerButton.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/form/date-field-dialog/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/form/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/hero/Hero.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/hero/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/posts/[postId]/_components/detail/Detail.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/posts/[postId]/_components/detail/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/posts/[postId]/_components/hero/Hero.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/posts/[postId]/_components/hero/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/posts/[postId]/_components/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/posts/[postId]/page.tsx
  src/app/(main)/event/board/create-post/_components/form/Form.tsx
  src/app/(main)/notice/create-post/_components/Form.tsx
  src/app/(main)/notice/posts/[postId]/_components/PostDetail.tsx
  src/app/(main)/notice/posts/[postId]/page.tsx
  src/components/feature/post/create-post-form/CreatePostForm.tsx
  src/components/feature/post/create-post-form/activity-date-dialog/index.ts
  src/components/feature/post/create-post-form/activity-date-dialog/trigger-button/index.ts
  src/components/feature/post/delete-dialog/DeleteDialog.tsx
  src/components/feature/post/delete-dialog/index.ts
  src/components/feature/post/index.ts
  src/components/feature/post/table/Table.tsx
  src/components/feature/post/table/TableContent.tsx
  src/components/feature/skeleton/BoardHero.tsx
  src/components/feature/skeleton/index.ts
  src/components/ui/calendar.tsx
  src/schema/post.ts
  src/service/api/post/activity.ts
  src/service/api/post/index.ts
  src/service/api/post/notice.ts
  src/service/api/post/post.ts
  src/service/models/Boards.ts
  src/service/models/Notices.ts
  src/service/models/Posts.ts
  src/service/models/data-contracts.ts
  src/service/models/index.ts
Labels: ♻️ refactor

#81 issue#68 게시판 리팩토링
  next.config.mjs
  src/app/(main)/_components/header/profile-button/dropdown-menu/DropdownMenu.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/board-list/BoardList.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/_components/create-board-button/CreateBoardButton.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/_components/BoardHero.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/page.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/posts/[postId]/_components/detail/Detail.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/form/Form.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/form/MultipleMemberSelect.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/page.tsx
  src/app/(main)/admin/layout.tsx
  src/app/(main)/event/_components/board-area/CreatePostButton.tsx
  src/app/(main)/event/board/create-post/page.tsx
  src/app/(main)/event/board/posts/[postId]/_components/post-detail/PostDetail.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/notice/_components/CreatePostButton.tsx
  src/app/(main)/notice/create-post/page.tsx
  src/app/(main)/notice/posts/[postId]/_components/PostDetail.tsx
  src/schema/board.ts
  src/service/config/instance.ts
  src/store/myInfo.ts
Labels: ♻️ refactor, 🎨 desgin

#84 Fix: 게시글 삭제, 추가 후 게시글 목록 query refetch
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/form/Form.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/posts/[postId]/_components/detail/Detail.tsx
  src/service/api/post/activity.ts
Labels: 🛠️ fix

#85 issue#5 post upload image
  src/app/(main)/activity/[semesterId]/[activityId]/boards/[boardId]/create-post/_components/form/Form.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/Skeleton.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/detail/BoardDetail.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/detail/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/form/Form.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/form/form-field/FormField.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/form/form-field/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/form/select-member-input/SelectMemberInput.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/form/select-member-input/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/form/select-member-input/multiple-member-select/MultipleMemberSelect.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/form/select-member-input/multiple-member-select/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/hero/BoardHero.tsx
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/hero/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/_components/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/create-board/page.tsx
  src/app/(main)/event/board/create-post/_components/form/Form.tsx
  src/app/(main)/notice/create-post/_components/Form.tsx
  src/components/feature/post/create-post-form/CreatePostForm.tsx
  src/components/feature/post/create-post-form/index.ts
  src/components/feature/post/form-field/index.ts
  src/components/feature/post/index.ts
  src/components/feature/post/post-editor/EditorField.tsx
  src/components/feature/post/post-editor/index.ts
  src/service/api/post/image-upload.ts
  src/service/models/PostImages.ts
  src/service/models/data-contracts.ts
Labels: 🎉 feat, ♻️ refactor

#87 issue#6 홈 화면 디자인
  next.config.mjs
  package-lock.json
  package.json
  public/crayon.svg
  public/haedal-background.png
  public/haedal-laptop.png
  src/app/(main)/_components/footer/Footer.tsx
  src/app/(main)/_components/footer/FooterDetail.tsx
  src/app/(main)/_components/main-section/RecruitSection.tsx
  src/app/(main)/_components/main-section/Section1.tsx
  src/app/(main)/_components/main-section/Section2.tsx
  src/app/(main)/_components/main-section/calender/Calender.tsx
  src/app/(main)/_components/main-section/calender/index.ts
  src/app/(main)/_components/main-section/carousel/Carousel.tsx
  src/app/(main)/_components/main-section/carousel/index.ts
  src/app/(main)/_components/main-section/eventsData.ts
  src/app/(main)/_components/main-section/index.ts
  src/app/(main)/activity/[semesterId]/[activityId]/ediit-board/page.tsx
  src/app/(main)/event/_components/carousel/Carousel.tsx
  src/app/(main)/event/_components/carousel/index.ts
  src/app/(main)/event/_components/index.ts
  src/app/(main)/page.tsx
  src/components/ui/carousel.tsx
  tailwind.config.ts
Labels: 🎉 feat, 🎨 desgin

#93 Fix: 댓글 페이징 버튼 추가
  frontend/src/components/feature/comment/Comment.tsx
  frontend/src/service/api/comment/comment.ts
Labels: 🛠️ fix

#94 Fix/#89 post image
  frontend/src/components/feature/post/post-editor/PostEditorField.tsx
  frontend/src/components/feature/post/post-editor/UpdateEditorField.tsx
  frontend/src/components/feature/post/post-editor/index.ts
  frontend/src/pages/activity-board/create-post/components/form/Form.tsx
  frontend/src/pages/activity-board/edit-post/components/form/Form.tsx
  frontend/src/pages/notice/create-post/_components/form/Form.tsx
  frontend/src/pages/notice/edit-post/components/form/Form.tsx
  frontend/src/service/schema/post.ts
  frontend/src/utils/get-image-name.ts
  frontend/src/utils/index.ts
Labels: 🛠️ fix

#100 fix: 관리자 페이지 리팩토링
  frontend/src/components/common/index.ts
  frontend/src/components/common/table/content/Content.tsx
  frontend/src/components/common/table/content/index.ts
  frontend/src/components/common/table/filter/Filter.tsx
  frontend/src/components/common/table/filter/index.ts
  frontend/src/components/common/table/index.ts
  frontend/src/components/common/table/pagination/Pagination.tsx
  frontend/src/components/common/table/pagination/index.ts
  frontend/src/components/feature/admin/index.ts
  frontend/src/components/feature/admin/member-table/index.ts
  frontend/src/components/feature/admin/member-table/not-found-table/NotFoundTable.tsx
  frontend/src/components/feature/admin/member-table/not-found-table/index.ts
  frontend/src/components/feature/admin/member-table/table-skeleton/TableSkeleton.tsx
  frontend/src/components/feature/admin/member-table/table-skeleton/index.ts
  frontend/src/components/feature/admin/member-table/table/MemberTable.tsx
  frontend/src/components/feature/admin/member-table/table/index.ts
  frontend/src/components/feature/index.ts
  frontend/src/components/feature/layout/admin/AdminLayout.tsx
  frontend/src/components/feature/layout/admin/Sidebar.tsx
  frontend/src/components/feature/layout/admin/index.ts
  frontend/src/components/feature/layout/admin/sidebar/index.ts
  frontend/src/components/feature/layout/main/MainLayout.tsx
  frontend/src/components/ui/sidebar.tsx
  frontend/src/pages/admin/member/components/approve-member-table/ApproveMemberTable.tsx
  frontend/src/pages/admin/member/components/approve-member-table/approve-member-button/ApproveButton.tsx
  frontend/src/pages/admin/member/components/approve-member-table/approve-member-button/index.ts
  frontend/src/pages/admin/member/components/approve-member-table/index.ts
  frontend/src/pages/admin/member/components/change-role-table/ChangRoleTable.tsx
  frontend/src/pages/admin/member/components/change-role-table/change-role-dialog/Dialog.tsx
  frontend/src/pages/admin/member/components/change-role-table/change-role-dialog/form/DialogForm.tsx
  frontend/src/pages/admin/member/components/change-role-table/change-role-dialog/form/index.ts
  frontend/src/pages/admin/member/components/change-role-table/change-role-dialog/index.ts
  frontend/src/pages/admin/member/components/change-role-table/index.ts
  frontend/src/pages/admin/member/components/expel-member-table/ExpelMemberTable.tsx
  frontend/src/pages/admin/member/components/expel-member-table/expel-member-dialog/Dialog.tsx
  frontend/src/pages/admin/member/components/expel-member-table/expel-member-dialog/form/DialogForm.tsx
  frontend/src/pages/admin/member/components/expel-member-table/expel-member-dialog/form/index.ts
  frontend/src/pages/admin/member/components/expel-member-table/expel-member-dialog/index.ts
  frontend/src/pages/admin/member/components/expel-member-table/index.ts
  frontend/src/pages/admin/member/components/index.ts
  frontend/src/pages/admin/member/components/member-table/content/index.ts
  frontend/src/pages/admin/member/components/member-table/filter/index.ts
  frontend/src/pages/admin/member/components/member-table/index.ts
  frontend/src/pages/admin/member/components/member-table/pagination/index.ts
  frontend/src/routes/Router.tsx
  frontend/src/routes/custom-route/admin/AdminRoute.tsx
  frontend/src/routes/custom-route/main/MainRoute.tsx
Labels: ♻️ refactor

#106 issue#102 Fix: 마이페이지 회원 role 포맷팅 안되는 버그
  frontend/src/pages/mypage/_components/user-info/UserInfoSection.tsx
Labels: 🛠️ fix

#108 Fix: 회원가입 schema 메세지 수정
  frontend/src/service/schema/auth.ts
Labels: 🛠️ fix

#109 Fix: 활동 관련 페이지에 suspense fallback 추가
  frontend/src/components/feature/activity/hero-skeleton/HeroSkeleton.tsx
  frontend/src/components/feature/activity/hero-skeleton/index.ts
  frontend/src/components/feature/activity/index.ts
  frontend/src/components/feature/activity/page-skeleton/PageSkeleton.tsx
  frontend/src/components/feature/activity/page-skeleton/index.ts
  frontend/src/components/feature/index.ts
  frontend/src/pages/activity-board/create-post/CreateActivityPostPage.tsx
  frontend/src/pages/activity-board/edit-post/EditActivityPostPage.tsx
  frontend/src/pages/activity-board/post/ActivityPostPage.tsx
  frontend/src/pages/activity/create-board/CreateBoardPage.tsx
  frontend/src/pages/activity/edit-board/EditBoardPage.tsx
  frontend/src/routes/Router.tsx
Labels: ♻️ refactor

#112 fix: 마이페이지 한 줄 소개 에러 문구 버그 수정
  frontend/src/pages/mypage/MyPage.tsx
  frontend/src/pages/mypage/_components/user-social-info/UserSocialInfoSection.tsx
  frontend/src/service/schema/mypage.ts
Labels: 🛠️ fix
