Repository KNU-HAEDAL-Website/frontend-v2, pull requests merged in 2025-08, with the labels that each got.

#159 해구르르 프로필 순서 수정 및 커스텀 훅 분리
  frontend/src/components/feature/member/member-card/MemberCard.tsx
  frontend/src/mock/admin/admin-profile.mock.ts
  frontend/src/mock/admin/index.ts
  frontend/src/mock/index.ts
  frontend/src/pages/member/default/MemberPage.tsx
  frontend/src/pages/recruit/RecruitPage.tsx
Labels: ♻️ refactor

#164 포맷팅 자동 검사와 자동 수정 기능 구현
  frontend/.gitignore
  frontend/.husky/pre-commit
  frontend/package.json
Labels: 📦 chore

#168 fix: 2025년 2학기의 부트캠프, 트랙 정보에 맞게 데이터 수정
  frontend/src/pages/recruit/components/bootcamp/accordion-card/AccordionCard.tsx
  frontend/src/pages/recruit/components/bootcamp/schedule-table/ScheduleTable.tsx
  frontend/src/pages/recruit/components/recruit-closed-hero/RecruitClosedHero.tsx
  frontend/src/pages/recruit/components/track/Track.tsx
Labels: 🛠️ fix

#172 Refactor/171 패키지매니저 pnpm으로 변경
  .github/workflows/ci.yml
  frontend/.husky/pre-commit
  frontend/.prettierignore
  frontend/package-lock.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/pages/main/components/animate-section/AnimateSection.tsx
  package-lock.json
  pnpm-lock.yaml
Labels: ♻️ refactor
